# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    pool:
      name: WSL-Ubuntu
    steps:
    - task: DotNetCoreCLI@2
      inputs:
       command: 'restore'
       projects: '**/src/**/*.csproj'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/src/**/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/**/*.csproj'
        arguments: '--collect "Code coverage"'
