# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

version: "3.7"

services:
  catalog-service:
    image: play-catalog-service
    build:
      context: ../Play.Catalog/src/Play.Catalog.Service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:5001;http://+:5000"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password123!"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      MONGO_CONNECTION_STRING: "mongodb://mongo:27017"
    depends_on:
      - mongo
    networks:
      - mynetwork
  inventory-service:
    image: play-inventory-service
    build:
      context: ../PLAY.INVENTORY/src/Play.Inventory.Service
      dockerfile: Dockerfile
    ports:
      - 5004:5004
      - 5005:500
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:6001;http://+:6000"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password123!"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      MONGO_CONNECTION_STRING: "mongodb://mongo:27017"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 5672
    depends_on:
      - mongo
    networks:
      - mynetwork
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    networks:
      - mynetwork

volumes:
  mongodbdata:
  rabbitmqdata:

networks:
  mynetwork:
