apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.catalogService.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.catalogService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.catalogService.name }}
    spec:
      containers:
      - name: {{ .Values.catalogService.name }}
        image: {{ .Values.catalogService.image }}:{{ .Values.catalogService.tag }}
        ports:
        - containerPort: {{ .Values.catalogService.port }}
        - containerPort: {{ .Values.catalogService.securePort }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: "https://+:{{ .Values.catalogService.securePort }};http://+:{{ .Values.catalogService.port }}"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "password123!"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/https/aspnetapp.pfx"
        - name: MONGO_CONNECTION_STRING
          value: {{ .Values.global.mongodb.connectionString }}
        - name: RABBITMQ_HOST
          value: {{ .Values.global.rabbitmq.host }}
        - name: RABBITMQ_PORT
          value: "{{ .Values.global.rabbitmq.port }}"
        - name: AllowedOrigin
          value: "http://playeconomy:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.catalogService.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.catalogService.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.catalogService.port }}
      targetPort: {{ .Values.catalogService.port }}
    - name: https
      protocol: TCP
      port: {{ .Values.catalogService.securePort }}
      targetPort: {{ .Values.catalogService.securePort }}