apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - name: {{ .Values.frontend.name }}
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: NODE_ENV
          value: development
        - name: CATALOG_SERVICE_URL
          value: {{ .Values.frontend.catalogServiceUrl }}
        - name: INVENTORY_SERVICE_URL
          value: {{ .Values.frontend.inventoryServiceUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}