apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
      - name: {{ .Values.mongodb.name }}
        image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}
        command: ["mongod"] # Note here
        args: ["--dbpath=/data/mongoaz"] # Note here 
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        volumeMounts:
        - name: mongodbdata
          mountPath: /data/mongoaz
      volumes:
      - name: mongodbdata
        persistentVolumeClaim:
          claimName: {{ .Values.mongodb.name }}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi # Adjust the size as needed
