apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
      - name: {{ .Values.mongodb.name }}
        image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        volumeMounts:
        - name: mongodbdata
          mountPath: /data/db
      volumes:
      - name: mongodbdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}