apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  serviceName: {{ .Values.mongodb.name }}--headless
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
      - name: {{ .Values.mongodb.name }}
        image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        volumeMounts:
        - name: mongodbdata
          mountPath: /data/db
      volumes:
      - name: mongodbdata
        persistentVolumeClaim:
          claimName: {{ .Values.mongodb.name }}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}--headless
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  type: ClusterIP
  clusterIP: None # Headless service for StatefulSet
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi # Adjust the size as needed
