apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
    spec:
      containers:
      - name: {{ .Values.rabbitmq.name }}
        image: {{ .Values.rabbitmq.image }}:{{ .Values.rabbitmq.tag }}
        ports:
        - containerPort: {{ .Values.rabbitmq.port }}
        - containerPort: {{ .Values.rabbitmq.managementPort }}
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.rabbitmq.name }}
  ports:
    - name: rabbitmq
      protocol: TCP
      port: {{ .Values.rabbitmq.port }}
      targetPort: {{ .Values.rabbitmq.port }}
    - name: management-port
      protocol: TCP
      port: {{ .Values.rabbitmq.managementPort }}
      targetPort: {{ .Values.rabbitmq.managementPort }}